//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace demo.Properties
{
    using System;
    using System.Collections.Generic;
    
    public partial class order_ispolnitel
    {
        public int id_order_ispolnitel { get; set; }
        public Nullable<int> user_id { get; set; }
        public Nullable<int> order_id { get; set; }
    
        public virtual Order Order { get; set; }
        public virtual Users Users { get; set; }
    }
}
