//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace demo.Properties
{
    using System;
    using System.Collections.Generic;
    
    public partial class Order
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Order()
        {
            this.order_ispolnitel = new HashSet<order_ispolnitel>();
        }
    
        public int id_order { get; set; }
        public Nullable<int> number { get; set; }
        public Nullable<System.DateTime> date_add_order { get; set; }
        public string status { get; set; }
        public Nullable<int> user_id { get; set; }
        public Nullable<System.DateTime> date_exit_order { get; set; }
        public string opisanie { get; set; }
        public string type { get; set; }
        public Nullable<int> object_id { get; set; }
        public string comment { get; set; }
    
        public virtual Object Object { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<order_ispolnitel> order_ispolnitel { get; set; }
    }
}
